/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import EDD.ListaSimple;
import EDD.NODO_AVL;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;
import javax.swing.DefaultListModel;
import usaclibrary.Books;

/**
 *
 * @author Guillermo
 */
public class FoundedBooks extends javax.swing.JFrame {

    /**
     * Creates new form FoundedBooks
     */
    int carne =0;
    String entry;
    int ISBN;
    DefaultListModel list;
    ListaSimple<Books> FoundShelf;
    public FoundedBooks() {
    }
    public FoundedBooks(String entry, int carne) {
        initComponents();
        this.FoundShelf = new ListaSimple<>();
        this.list = new DefaultListModel();
        this.carne=carne;
        jLabel1.setText("Coincidencias de títulos con :"+entry);
        this.entry=entry;
        FindBooks(entry);
        PointerInfo a = MouseInfo.getPointerInfo();
        Point b = a.getLocation();
        int x = (int) b.getX();
        int y = (int) b.getY();
        this.setLocation(x-200, y-200);
    }
     public FoundedBooks(int ISBN, int carne) {
        initComponents();
        this.FoundShelf = new ListaSimple<>();
        this.list = new DefaultListModel();
        this.carne=carne;
        jLabel1.setText("Coincidencias de ISBN con :"+Integer.toString(ISBN));
        this.ISBN=ISBN;
        FindBooksByISBN(ISBN);
        PointerInfo a = MouseInfo.getPointerInfo();
        Point b = a.getLocation();
        int x = (int) b.getX();
        int y = (int) b.getY();
        this.setLocation(x-200, y-200);
    }
    void FindBooksByISBN(int ISBN){
        list.clear();
        this.FoundShelf = new ListaSimple();
        visitTree(usaclibrary.USACLibrary.PublicLibrary.getRoot(), this.FoundShelf, this.ISBN);        
        populateList(this.FoundShelf);
        jList1.setModel(list);
    }
    void FindBooks(String x){        
        list.clear();
        this.FoundShelf = new ListaSimple();
        visitTree(usaclibrary.USACLibrary.PublicLibrary.getRoot(), this.FoundShelf, this.entry);        
        populateList(this.FoundShelf);
        jList1.setModel(list);
    }
    void populateList(ListaSimple<Books> x){
        list.clear();
        for(int i =0;i<x.getSize();i++){
            list.addElement(x.elementAt(i).getTitulo()+"\t| "+x.elementAt(i).getCategoria());
        }        
        jList1.setModel(list);
    }
    void visitTree(NODO_AVL x, ListaSimple<Books> y, int z){
        if(x==null){
            return;
        }
        if(x.getColeccion().Search(z)!=null){
            y.AddLast(x.getColeccion().Search(z));
        }        
        if(x.getLeft()!=null){
            visitTree(x.getLeft(), y, z);
        }
        if(x.getRight()!=null){
            visitTree(x.getRight(), y, z);
        }
    }
    void visitTree(NODO_AVL x, ListaSimple<Books> y, String z){
        if(x==null){
            return;
        }
        x.getColeccion().SearchAlikeTitle(x.getColeccion().getRoot(), z, y);
        if(x.getLeft()!=null){
            visitTree(x.getLeft(), y, z);
        }
        if(x.getRight()!=null){
            visitTree(x.getRight(), y, z);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Actualizar Lista");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        int chosen = jList1.getSelectedIndex();
        Books selected = this.FoundShelf.elementAt(chosen);
        BookDisplay showBook = new BookDisplay(this.carne, selected);
        showBook.show();
    }//GEN-LAST:event_jList1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        FindBooks(this.entry);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoundedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoundedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoundedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoundedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoundedBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
