/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import static EDD.AVL.NextNodos;
import static EDD.AVL.writeDOC;
import static EDD.Block.indexControl;
import EDD.Nodo;
import java.awt.BorderLayout;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import usaclibrary.USACLibrary;

/**
 *
 * @author Guillermo
 */
public class ReportManage extends javax.swing.JFrame {

    /**
     * Creates new form ReportManage
     */
    public ReportManage() {
        initComponents();
        PointerInfo a = MouseInfo.getPointerInfo();
        Point b = a.getLocation();
        int x = (int) b.getX();
        int y = (int) b.getY();
        this.setLocation(x-200, y-200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jButton1.setText("Imprimir Árboles B");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Imprimir Árbol AVL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Imprimir Tabla Hash");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Nodos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Recorridos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("BlockChain");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(418, 347));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        try {
            usaclibrary.USACLibrary.PublicLibrary.PrintAllBTrees(usaclibrary.USACLibrary.PublicLibrary.getRoot());
            ViewGallery v = new ViewGallery();
            v.show();
        } catch (IOException ex) {
            Logger.getLogger(UserUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            usaclibrary.USACLibrary.PublicLibrary.GraphTree();
            JFrame fr = new JFrame();
            fr.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            BufferedImage img=null;
            try {
                img = ImageIO.read(new File("Graphics\\AVL.png"));
            } catch (Exception e) {
            }
            JLabel lbl =  new JLabel("Árbol AVL");
            lbl.setIcon(new ImageIcon(img));
            JScrollPane jsp = new JScrollPane(lbl);
            fr.getContentPane().add(jsp, BorderLayout.CENTER);
            fr.pack();
            fr.setLocationRelativeTo(this);
            fr.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ReportManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            usaclibrary.USACLibrary.StudentTable.GraphTable();
            JFrame fr = new JFrame("Tabla Hash");
            fr.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            BufferedImage img=null;
            try {
                img = ImageIO.read(new File("Graphics\\HashTable.png"));
            } catch (Exception e) {
            }
            JLabel lbl =  new JLabel();
            lbl.setIcon(new ImageIcon(img));
            JScrollPane jsp = new JScrollPane(lbl);
            fr.getContentPane().add(jsp, BorderLayout.CENTER);
            fr.pack();
            fr.setLocationRelativeTo(this);
            fr.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ReportManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Nodo<String> aux = usaclibrary.USACLibrary.Nodos.getHead();
        Nodo<String> aux2=null;
        String content ="";
        String content2="";
        while(aux!=null){
            if(aux2!=null){
                content2+="\""+aux.getValue()+"\" -> \""+aux2.getValue()+"\";";
            }
            if(aux.getRight()==null){                
                content+="\""+aux.getValue()+"\""+";";
            }else{
                content+="\""+aux.getValue()+"\" ->";
            }
            aux2=aux;
            aux=aux.getRight();
        }
        String head = "digraph G {\n nodesep=0.3;\n ranksep=0.2;\n    margin=0.1;\n node[shape=box width=\"1.5\" height=\"1.5\" fixed=\"true\"];  edge [arrowsize=0.8];";       
        head += content+content2+"}";
        try {
            writeDOC(head);
        } catch (IOException ex) {
            Logger.getLogger(ReportManage.class.getName()).log(Level.SEVERE, null, ex);
        }
        File dir = new File("Graphics");
        dir.mkdirs();
        dir = new File("TextFiles");
        dir.mkdirs();            
        File temporal = new File(dir, "NODOS.dot");
        try (FileWriter TemporalFile = new FileWriter(temporal)) {
            TemporalFile.write(head);
        } catch (IOException ex) {
            Logger.getLogger(ReportManage.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            temporal.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(ReportManage.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {            
            ProcessBuilder pbuilder;
            pbuilder = new ProcessBuilder("dot", "-Tpng", "-o", "Graphics\\NODOS.png","TextFiles\\NODOS.dot");
            pbuilder.redirectErrorStream(true);
            pbuilder.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
        JFrame fr = new JFrame("Nodos de la Red");
        fr.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        BufferedImage img=null;
        try {
            img = ImageIO.read(new File("Graphics\\NODOS.png"));
        } catch (Exception e) {
        }
        JLabel lbl =  new JLabel();
        lbl.setIcon(new ImageIcon(img));
        JScrollPane jsp = new JScrollPane(lbl);
        fr.getContentPane().add(jsp, BorderLayout.CENTER);
        fr.pack();
        fr.setLocationRelativeTo(this);
        fr.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            USACLibrary.PublicLibrary.Imprimir();
        } catch (IOException ex) {
            Logger.getLogger(ReportManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String head = "digraph G {\n nodesep=0.3;\n ranksep=0.2;\n    margin=0.1;\n node[shape=box width=\"1.5\" height=\"1.5\" fixed=\"true\"];  edge [arrowsize=0.8];";
        JSONParser parser = new JSONParser();
        String labels="";
        for(int i =1;i<indexControl;i++){
                            File dir = new File("BLOCKS");
                            dir.mkdirs();
                            File myObj = new File(dir, "BLOCK_"+Integer.toString(i)+".json");
                            Object obj;
            try {
                obj = parser.parse(new FileReader(myObj));
                JSONObject jsonObj = (JSONObject) obj;
                head+=Integer.toString(i);
                head +=(i<indexControl-1)? "->":";";
                labels+=Integer.toString(i)+"[label=\"INDEX: "+jsonObj.get("INDEX")+"\\n TIMESTAMP: "+jsonObj.get("TIMESTAMP")
                        +"\\n NONCE: "+jsonObj.get("NONCE")+"\\n PREVIOUSHASH: "+jsonObj.get("PREVIOUSHASH")+"\\n HASH: "+jsonObj.get("HASH")+"\"];\n";
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ReportManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ReportManage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(ReportManage.class.getName()).log(Level.SEVERE, null, ex);
            }
                            
                    }
        File dir = new File("Graphics");
        dir.mkdirs();
        dir = new File("TextFiles");
        dir.mkdirs();            
        File temporal = new File(dir, "BLOCKHAIN.dot");
        try (FileWriter TemporalFile = new FileWriter(temporal)) {
            TemporalFile.write(head+labels+"}");
        } catch (IOException ex) {
            Logger.getLogger(ReportManage.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            temporal.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(ReportManage.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {            
            ProcessBuilder pbuilder;
            pbuilder = new ProcessBuilder("dot", "-Tpng", "-o", "Graphics\\BLOCKHAIN.png","TextFiles\\BLOCKHAIN.dot");
            pbuilder.redirectErrorStream(true);
            pbuilder.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
        JFrame fr = new JFrame("BLOCKHAIN");
        fr.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        BufferedImage img=null;
        try {
        img = ImageIO.read(new File("Graphics\\BLOCKHAIN.png"));
        } catch (Exception e) {
        }
        JLabel lbl =  new JLabel();
        lbl.setIcon(new ImageIcon(img));
        JScrollPane jsp = new JScrollPane(lbl);
        fr.getContentPane().add(jsp, BorderLayout.CENTER);
        fr.pack();
        fr.setLocationRelativeTo(null);
        fr.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    // End of variables declaration//GEN-END:variables
}
